-- SQL insert statements for sample blogs (matching the current blogs table schema)
INSERT INTO blogs (id, title, content, thumbnail, video_url, created_at, views, tags, type)
VALUES
(uuid_generate_v4(),
 'Building Modern Web Applications with Next.js 14',
 '# Building Modern Web Applications with Next.js 14\n\nNext.js 14 brings exciting new features and improvements...',
 '/placeholder.jpg',
 '',
 NOW(),
 0,
 ARRAY['nextjs', 'react', 'web-development'],
 'Tutorial'),

(uuid_generate_v4(),
 'Mastering TypeScript for Scalable Applications',
 '# Mastering TypeScript\n\nTypeScript helps you build scalable and maintainable applications...',
 '/placeholder.jpg',
 '',
 NOW(),
 0,
 ARRAY['typescript', 'javascript', 'web-development'],
 'Tutorial'),

(uuid_generate_v4(),
 'React Native vs Flutter: A 2024 Comparison',
 '# React Native vs Flutter\n\nComparing two leading cross-platform mobile frameworks...',
 '/placeholder-user.jpg',
 '',
 NOW(),
 0,
 ARRAY['react-native', 'flutter', 'mobile-development'],
 'Opinion'),

(uuid_generate_v4(),
 'How I Built My Developer Portfolio with Supabase',
 '# Building a Portfolio with Supabase\n\nA step-by-step guide to using Supabase for your portfolio backend...',
 '/placeholder-logo.png',
 '',
 NOW(),
 0,
 ARRAY['supabase', 'portfolio', 'web-development'],
 'Project Update'),

(uuid_generate_v4(),
 'Announcing My New Open Source Project: DevToolsX',
 '# Announcing DevToolsX\n\nIntroducing a new open source toolkit for developers...',
 '/placeholder-logo.svg',
 '',
 NOW(),
 0,
 ARRAY['tools', 'open-source', 'announcement'],
 'Announcement'),

(uuid_generate_v4(),
 'Interview: Insights from a Senior React Developer',
 '# Interview with a Senior React Developer\n\nValuable lessons and tips from an industry expert...',
 '/placeholder-user.jpg',
 '',
 NOW(),
 0,
 ARRAY['interview', 'react', 'career'],
 'Interview'),

(uuid_generate_v4(),
 'Case Study: Scaling a SaaS App with Node.js',
 '# Scaling SaaS with Node.js\n\nA real-world case study on scaling a SaaS application...',
 '/placeholder.jpg',
 '',
 NOW(),
 0,
 ARRAY['nodejs', 'case-study', 'saas'],
 'Case Study'),

(uuid_generate_v4(),
 'Productivity Tools Every Developer Should Know',
 '# Productivity Tools\n\nA roundup of the best productivity tools for developers in 2024...',
 '/placeholder.svg',
 '',
 NOW(),
 0,
 ARRAY['productivity', 'tools', 'web-development'],
 'Opinion'),

(uuid_generate_v4(),
 'Getting Started with GSAP Animations in React',
 '# GSAP Animations in React\n\nLearn how to add smooth animations to your React apps using GSAP...',
 '/placeholder-logo.png',
 '',
 NOW(),
 0,
 ARRAY['gsap', 'react', 'animation'],
 'Tutorial'),

(uuid_generate_v4(),
 'From HTML to React: My Learning Journey',
 '# From HTML to React\n\nSharing my experience transitioning from static HTML to modern React apps...',
 '/placeholder-user.jpg',
 '',
 NOW(),
 0,
 ARRAY['html', 'react', 'learning'],
 'Opinion'); 