INSERT INTO blogs (id, title, slug, content, excerpt, thumbnail, video_url, created_at, views, tags, type)
VALUES
-- OPINION
(uuid_generate_v4(),
 'Why JavaScript Will Remain the Language of the Web',
 'why-javascript-will-remain-the-language-of-the-web',
 '# Why JavaScript Will Remain the Language of the Web\n\nIn this opinion piece, we explore the enduring strengths of JavaScript and why it continues to dominate web development.',
 'In this opinion piece, we explore the enduring strengths of JavaScript and why it continues to dominate web development.',
 'https://en.m.wikipedia.org/wiki/File:Unofficial_JavaScript_logo_2.svg',
 'https://www.youtube.com/watch?v=2Ji-clqUYnA',
 NOW(),
 0,
 ARRAY['javascript', 'web', 'opinion'],
 'Opinion'),

-- CASE STUDY
(uuid_generate_v4(),
 'Case Study: Scaling an E-Commerce Site to Handle 1M Users',
 'case-study-scaling-ecommerce-site-1m-users',
 '# Case Study: Scaling an E-Commerce Site to Handle 1M Users\n\nWe analyze the architectural decisions and technologies that enabled scaling an e-commerce platform to support millions of users.',
 'We analyze the architectural decisions and technologies that enabled scaling an e-commerce platform to support millions of users.',
 '/images/case-study-ecommerce.jpg',
 'https://youtu.be/ejofP2VKu-4',
 NOW(),
 0,
 ARRAY['case-study', 'scaling', 'ecommerce'],
 'Case Study'),

-- INTERVIEW
(uuid_generate_v4(),
 'Interview with Vercel Founder on the Future of Serverless',
 'interview-vercel-founder-future-serverless',
 '# Interview with Vercel Founder on the Future of Serverless\n\nWe sat down with Guillermo Rauch, founder of Vercel, to discuss the evolution and future of serverless computing.',
 'We sat down with Guillermo Rauch, founder of Vercel, to discuss the evolution and future of serverless computing.',
 '/images/interview-vercel.jpg',
 'https://youtu.be/MQw_zncxk-E',
 NOW(),
 0,
 ARRAY['interview', 'serverless', 'vercel'],
 'Interview'),

 -- OPINION
(uuid_generate_v4(),
 'Why React Continues to Dominate Frontend Development',
 'why-react-continues-dominate-frontend-development',
 '# Why React Continues to Dominate Frontend Development\n\nIn this opinion piece, we explore why React remains the most popular frontend framework despite growing competition.',
 'In this opinion piece, we explore why React remains the most popular frontend framework despite growing competition.',
 '/images/opinion-react.jpg',
 'https://www.youtube.com/watch?v=Ke90Tje7VS0',
 NOW(),
 0,
 ARRAY['react', 'frontend', 'opinion'],
 'Opinion'),

-- CASE STUDY
(uuid_generate_v4(),
 'Case Study: Migrating a Legacy App to React',
 'case-study-migrating-legacy-app-react',
 '# Case Study: Migrating a Legacy App to React\n\nThis case study walks through the process, challenges, and benefits of migrating a large legacy web app to React.',
 'This case study walks through the process, challenges, and benefits of migrating a large legacy web app to React.',
 '/images/case-study-react-migration.jpg',
 'https://www.youtube.com/watch?v=DLX62G4lc44',
 NOW(),
 0,
 ARRAY['react', 'migration', 'case-study'],
 'Case Study'),

-- INTERVIEW
(uuid_generate_v4(),
 'Interview with React Core Team Member on React 18',
 'interview-react-core-team-member-react-18',
 '# Interview with React Core Team Member on React 18\n\nWe interview a React core team engineer about what went into React 18 and what the future holds.',
 'We interview a React core team engineer about what went into React 18 and what the future holds.',
 '/images/interview-react-team.jpg',
 'https://www.youtube.com/watch?v=YkOSUVzOAA4',
 NOW(),
 0,
 ARRAY['react', 'react18', 'interview'],
 'Interview');
